# Generated by Django 4.0.4 on 2022-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_alter_funding_funding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
